# Generated by Django 4.2 on 2023-07-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaceInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyelid", models.CharField(max_length=20, null=True)),
                ("do", models.CharField(max_length=20)),
                ("sr", models.CharField(max_length=20)),
                ("pn", models.CharField(max_length=20)),
                ("wt", models.CharField(max_length=20)),
                ("type_list", models.CharField(max_length=20, null=True)),
                ("image", models.ImageField(null=True, upload_to="media/post_images")),
                ("user_id", models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NameAge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("age", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
            ],
        ),
    ]
